name: .run-project

on:
  schedule:
    - cron: '0,30 8-16 * * *'
    - cron: '0 17 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.*

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --no-build

    - name: Execute Program
      run: dotnet run MirrorDatabase # Reemplaza con tu nombre de proyecto o ruta
